### ISSUE TITLE
「全角标点压缩」导致的字符重叠

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#101]
![image](https://cloud.githubusercontent.com/assets/5090766/24655565/4ee18ce8-1971-11e7-8f88-4c6fe4aeea9b.png)
[思源宋体](https://source.typekit.com/source-han-serif/cn/)

如何调整压缩比率来避免字符重叠呢？

**Comment by stecue** [comment]
可以调节 kern_* 系列变量。对于连续的标点，调节 kern_consec_*。对于孤立的标点调一下 kern_ind_open 和 kern_ind_close 就可以了。这对所有网页都生效。但是思源宋体的网页直接让标点显示成半角，这就很有意思了……

**Comment by stecue** [comment]
哈，原来Noto Sans/Noto Serif字体可以开启内置kerning——这下子标点压缩就容易了。很多“变通方案”导致的bugs也一并可以解决。FixCJK! 2.0就这么办。

**Comment by stecue** [comment]
1.2.x 分支的 [1.1.80](https://github.com/stecue/fixcjk/blob/1.2.x/FixCJK!.user.js) 已初步启用内置 kerning 功能，可以试一下。

**Comment by Explorare** [comment]
忘记说这件事了。这个是 OpenType 的特性，包括 “proportional alternate width (palt)", "proportional Kana (pkna)" 和 "kerning"，详见 [Syntax for OpenType features in CSS](https://helpx.adobe.com/typekit/using/open-type-syntax.html)
如果新脚本能尽可能支持 OpenType 的新特性就再好不过了。日本的字体普遍采用 OpenType，很多都支持 `palt` 和 `pkna` 的。
[文字詰めできるCSSのfont-feature-settingsが凄い！ 日本語フォントこそ指定したい自動カーニング - ICS MEDIA](https://ics.media/entry/14087/3)

**Comment by stecue** [comment]
Thanks! 日本人主导的思源字体之前的中文字体全是等宽，也没有kerning。看来说日本人有工匠精神至少在字体这方面没错。

之前有人反映雅黑处理日文不好，我就把日文网页的脚本禁用了，嗯……

**Comment by Explorare** [comment]
中文字体本来就应该是等宽的吧，比例主要是针对假名和西文字符。假名用比例特性可以有效压缩间距并且不影响可读性，还是挺不错的。

**Comment by Explorare** [comment]
能否专门提供一个参数来设定是否默认开启 `palt` 呢？如果能提供类似  `font-feature-settings: "palt"` 来配置多个 OpenType Fonts 的特性就更好了。另外字体替换后的 italic 是调用了 italic 字体么？还是渲染的斜体？另外希望能提供一个参数来默认启用「自动空格」。谢谢了。

**Comment by Explorare** [comment]
另外我设定了 `CJKdefault = '"Source Han Serif SC Regular"'`，Advanced Font Settings 中的 Standard 同样设为此字体，但 Twitter 上还是用了 Source Han Sans SC Regular，是因为此页面默认了 Sans-serif 么？能否自动替换正文字体为 Serif 呢？
[开启了 palt 的思源黑体、思源宋体的显示效果](https://bgm.tv/group/topic/342533)

**Comment by stecue** [comment]
等宽有两重含义：字符等宽和没有kerning。中文汉字是天然等宽的，但是中文标点不是等宽的。或者即使等宽，也应该具有 kerning 的。

**Comment by stecue** [comment]
从我这边看，https://twitter.com/kahasina9 网页上的字体是 “Arial,sans-serif”。
所以默认就是 sans-serif，无衬线字体。你要想把 sans-serif 也改成 Source Han Serif SC Regular，得改 CJKsans。但是这样所有应用脚本的网页的 sans-serif 也都改了。

**Comment by Explorare** [comment]
所以我就在想啊，我常去的网站就 Twitter 和 Feedly，如果能针对特定网站的特定元素覆盖字体为特定字体就好了，白名单。

**Comment by stecue** [comment]
作为临时的work around，你可以把@name 改个名，比如FixCJK!_Twitter什么的，然后在@match那里就写twitter什么的，另存为新的脚本并导入。
然后在原脚本那里的@exclude写上twitter什么的。最后同时启用两个脚本。

当然好像白名单什么的，greasemonkey 和 tampermonkey自己就可以设置，似乎并不需要改脚本（名字除外）。

**Comment by stecue** [comment]
`palt` 对标点一定是开启的。对于非标点文字，[1.1.86](https://github.com/stecue/fixcjk/blob/1.2.x/FixCJK!.user.js)之后用`usePaltForCJKText`和`usePaltForAll`控制开启。`forceAutoSpaces`控制是否不需双击就可以自动空格。（默认已开启）
字体替换之后的斜体要看替换进去的字体有没有自带斜体。Noto Sans/Serif CJK系列似乎并没有斜体。

**Comment by Explorare** [comment]
默认开启 palt 后发现会导致自动空格几乎无效果，如图

![](https://i.imgur.com/JMIasfL.png)

**Comment by stecue** [comment]
有效果啊，不是有空格么？空格小是不是因为你把`usePaltForCJKText`或者`usePaltForAll`也开了？

另外能附上URL么？我似乎google不到完全一样的网页。

**Comment by Explorare** [comment]
是有空格，但空格因为开了 palt 基本被压缩到不见，这就有点尴尬了。这个页面是 Feedly 中的。

**Comment by stecue** [comment]
我可以加一个长一点的空格的选项试试看……Feedly没有对外的URL么？看贴图猜效果有点麻烦……

**Comment by Explorare** [comment]
并没有这样的选项，原页面在这里 http://acg.178.com/201704/285469177735.html，你可以在 Feedly 上添加 178 的源找这篇。
另外我发现所有 bold 字体都变成了思源宋体，脚本中是这样写的，按理来说加粗也应该是思源黑体啊
```
var CJKdefault = '"Source Han Sans SC Regular","Microsoft YaHei",SimSun,"WenQuanYi Zen Hei Sharp","WenQuanYi Micro Hei"'; //The default CJK font if no sans or serif is specified. Regular weight.
var CJKSimSun= '"Source Han Serif SC","Microsoft YaHei","Note Serif CJK SC","WenQuanYi Micro Hei"'; //Fonts to replace SimSun;
var CJKserif = '"Source Han Serif SC","Microsoft YaHei","WenQuanYi Micro Hei"'; //Default serif fonts for CJK. Although It is intended for regular weight but some element with bold weight still use the font here. Therefore "SimSun" itself is not a good choice because it does not have a real bold font.
var CJKsans = '"Source Han Sans SC Regular","Microsoft YaHei","Noto Sans CJK SC","Noto Sans CJK SC Regular"'; //Sans-serif fonts for CJK. Regular weight.
var CJKBold = '"Source Han Sans SC Regular","Microsoft YaHei","WenQuanYi Micro Hei"'; //The "good CJK font" to replace SimSun bold. Note that some elements still use font in CJKserif defined above such as the menus on JD.com.
var CJKPunct = 'Source Han Sans SC Regular,SimHei,SimSun'; //The font to use for CJK quotation marks.
var LatinInSimSun = 'Source Han Serif SC'; //The Latin font in a paragraph whose font was specified to "SimSun" only.
var LatinSans = '"Source Sans Pro","Open Sans","PT Sans",Lato,Verdana,Arial'; //Sans-serif fonts for Latin script. It will be overridden by  a non-virtual font in the CSS font list if present.
var LatinSerif = '"Source Serif Pro","PT Serif",Constantia,"Liberation Serif","Times New Roman"'; //Serif fonts for Latin script. It will be overridden by  a non-virtual font in the CSS font list if present.
var LatinMono = 'Consolas,"DejaVu Sans Mono"'; //Monospace fonts for Latin script. It will be overridden by  a non-virtual font in the CSS font list if present.
var FixRegular = true; //Also fix regular fonts. You need to keep this true if you want to use "LatinInSimSun" in Latin/CJK mixed context.
var FixMore = true; //Appendent CJK fonts to all elements. No side effects found so far.
var FixPunct = true; //If Latin punctions in CJK paragraph need to be fixed. Usually one needs full-width punctions in CJK context. Turn it off if the script runs too slow or HTML strings are adding to your editing area.
///=== Experimental Options. The following options are for experienced users.===///
var usePaltForCJKText = true; //If apply "palt" to CJK text (not only puncts) as well.
var usePaltForAll = false; //If apply "palt" to as much elements as possible.
var useJustify = false; //Make justify as the default alignment.
var forceAutoSpaces = true; //if enabled, no need to double-click to add spaces.
```

![image](https://cloud.githubusercontent.com/assets/5090766/24756113/3a08e9c0-1b0f-11e7-9613-10b269f857b1.png)
[ep.1 魔の山へ / サクラクエスト](https://bgm.tv/ep/705296#post_475544)

**Comment by stecue** [comment]
不太清楚，但是Source Han Sans SC Regular 这种写法感觉不太对，一般不需要写"Regular"。大部分情况下Regular是字体的style，不是font-family的一部分。

**Comment by Explorare** [comment]
可这套字体有个 Regular 还有个 Normal，Regular 稍微粗了一点。
去掉 Regular 后是这个样子
![image](https://cloud.githubusercontent.com/assets/5090766/24757599/42c38afe-1b12-11e7-99e4-5ccf6df7fb0c.png)

用了这个脚本后用 Chrome 的字体插件看到的全是 General Punct - Regular，不放特别大有点难看出字体区别。

试了一下发现粗体部分 General Punct - Bold 应用了 `CJKSimSun` 的字体，这里我如果换成思源黑体则上面的粗体同样变成思源黑体。可 General Punct - Bold 不应该应用的是 `CJKBold` 么。

**Comment by Explorare** [comment]
找到问题了
line 145
```
var qBold = LatinInSimSun + ',' + CJKBold + ',' + qsig_bold;
```
可以看到 qBold 中 LatinInSimSun 是最高优先级，如果这里用了包含 CJK 的字体则会导致没法 fallback 到`CJKBold`，所以`LatinInSimSun`应该配置为`Source Serif Pro`而不是`Source Han Serif SC`。

**Comment by stecue** [comment]
OK，现在可以开启从`useBroaderSpaces`到`use3XBroaderSpaces`的选项来使用不同宽度的空格了。（[1.1.91](https://github.com/stecue/fixcjk/blob/1.2.x/FixCJK!.user.js)）

**Comment by stecue** [comment]
嗯，LatinInSimSun 的意思就是Latin字体哈。看来应该在注释里强调一下。
