### ISSUE TITLE
对于快速刷新内容的页面的支持

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#105]
今天在用 Slack （一款 Web 端协作、聊天工具）时发现新出现的内容并不能及时得到渲染，而是在双击之后重新检查页面才会渲染，所以是否能自动检测页面变动来渲染变动的内容呢？

**Comment by stecue** [comment]
用鼠标滚动页面时就会触发重新检查，但不会修正标点。单击可以修正标点（以及在开启了`forceAutoSpaces`时修正尽可能多的空格），不需要双击。长按鼠标再松开会忽略所有时间限制重新检查。

我在`1.2.3`加了一个`scrollToFixAll`选项，如果你觉得不影响性能可以开启。如果刷新速度还不够，我可以再调整一下参数，或者让脚本定时检查页面。

**Comment by Explorare** [comment]
ScrollToFixAll 监听的是用户的滚动事件还是页面的自动滚动？如果是后者的话似乎并没起作用。滚轮滚动似乎也没效果。功能确实开了，保存并刷新了页面。如果需要测试环境请发邮件到 explorare@hencolle.com，我给你发 Slack 邀请。谢谢了。
另外脚本每次更新都会重置我的字体配置和参数设置，有没有好办法能避免呢？

**Comment by stecue** [comment]
理论上任何页面滚动都可以。我把滚动触发的函数重新改了一下(`1.2.4`)，理论上跟单击应该没有区别。我在[知乎](https://www.zhihu.com)上测是可用的。知乎的主页可以一直往下拖，它会一直更新。如果新出现的内容没有修正到，可能是因为浏览器跑脚本太慢，超时了…… Firefox 会有这种情况，chrome 就少见。你可以用`F12`打开控制台看看FixCJK的输出。如果正常完成检查会输出
`FixCJK!: NORMAL TERMINATION...`
否则可能会看到
`"FIXME: Only XXX tested in total on...`

另外我的邮件就是 stecue@gmail.com。

**Comment by stecue** [comment]
这些配置相当于硬编码到源代码里的，所以更新时必然被重置。以前想让脚本直接读取本地配置文件，但似乎Greasmonkey/Tampermonkey没这功能。可能有类似的功能我当时没找到，我有空再去看看。

**Comment by Explorare** [comment]
Fixed at #107
