### ISSUE TITLE
Conflict with "Advanced Font Settings"

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#107]
原标题：FixPunct 功能失效
Chromium version: 57.0.2987.110
Script version: 1.1.52/1.2.0/1.2.3/1.2.4
Conf:
```
var CJKdefault = '"Source Han Sans SC"'
var CJKSimSun= '"Source Han Serif SC"'
var CJKserif = '"Source Han Serif SC"'
var CJKsans = '"Source Han Sans SC"'
var CJKBold = '"Source Han Sans SC"'
var CJKPunct = 'Noto Sans CJK SC'

var LatinInSimSun = 'Source Serif Pro'
var LatinSans = '"Source Sans Pro"'
var LatinSerif = '"Source Serif Pro"'
var LatinMono = 'Consolas'

var FixRegular = true;
var FixMore = true;
var FixPunct = true;

var usePaltForCJKText = true;
var usePaltForAll = false;
var useJustify = false;
var forceAutoSpaces = true;
```

![image](https://cloud.githubusercontent.com/assets/5090766/24838671/407c2700-1d7f-11e7-9c31-51a04baa111a.png)
Source: Feedly

是我配置有问题了么，突然发现 FixPunct 功能不能用了（其实最早就是为了这个功能才发现这个脚本的）。另外那个符号就是 U+2019 单引号。

---
刚才突然想到会不会是因为结果被 Advanced Font Settings 覆盖了，就关掉了这个插件，问题消失。同时之前反馈的 Slack/Feedly 中渲染延迟、需要双击重新渲染的问题也消失了。

**Comment by stecue** [comment]
啊？理论上Advanced Font Settings只管指定了"lang"属性元素的sans、serif等虚拟字体的映射，不会去修改元素本身的css font-family属性，我这里从来没有出过问题……

**Comment by stecue** [comment]
我看了，那个标题没有lang属性，字体是sans。不使用脚本的话显示的就应该是Advanced Font Settings里default语言的sans字体。如果default的设置是Noto Sans CJK SC或者Source Han CJK SC之类的中文字体，英文单引号就显示成全角字符了。

**Comment by stecue** [comment]
你的截图里的标题很像应用了Noto Sans CJK SC/Source Han Sans SC的结果。另外FixCJK对于新出现的元素是只管中文的，这样可以快一点。所以即使开了脚本，FixCJK也不会去修正标题中的纯英文字体。如果Advanced Font Settings里设置不对，那就保持那个样子了……我有空可以去看一下是否能再加个选项以强制修改非中文元素。

**Comment by Explorare** [comment]
Advanced Font Settings 中的 default 确实是 Source Han Sans SC。所以说如果我把默认换成 Source Sans Pro 就好了么？

**Comment by stecue** [comment]
应该就好了。default中的字体不应该是中文字体。

**Comment by stecue** [comment]
嗯，现在（`1.2.5+`）开启`scrollToFixAll`之后连英文也可以一起修改了。
