### ISSUE TITLE
Not work on v2ex.com and myfleet.moe

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#110]
V2EX 帖子正文无法被替换字体，底部回复栏的【回复】倒是被替换了。
![image](https://cloud.githubusercontent.com/assets/5090766/24911388/540f0718-1efd-11e7-9cd2-ee70b603e1e1.png)

myfleet.moe 的所有文字都没有被替换
![image](https://cloud.githubusercontent.com/assets/5090766/24911369/41ac8ac8-1efd-11e7-87bc-e96cff901f89.png)
[任務 -Explorare提督-](https://myfleet.moe/user/12138544/quest)

**Comment by stecue** [comment]
嗯，这是“跳过日文设定”的“feature”，因为有人觉得中文字体应用到日文部分不好看，参看 #100 。
Anyway，我加了一个`skipJaLang`的选项（1.2.8+），默认`false`。如果需要在浏览器里自定义日文字体，改成`true`就好了。

**Comment by stecue** [comment]
[1.2.11+](https://github.com/stecue/fixcjk/blob/1.2.x/FixCJK!.user.js) 中增加了`KanaSerif`和`KanaSans`用于控制假名字体，并默认开启假名的比例宽度模式，在我看来效果还行。(#100)
