### ISSUE TITLE
关于默认字体的选择和排序

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#111]
5d78aad1cc4374a474696ee68922e401da21c730 中添加了 Source Han Sans CN 作为 Microsoft Yahei 的 fallback，请问这个选择的理由是？我的建议是使用 Source Han Sans/Serif SC 而不是 CN，因为 Source Han Sans SC 属于 Language-specific OpenType，包含所有 65,535 个字形

>This deployment configuration is available in four languages—Simplified Chinese, Traditional Chinese, Japanese,
and Korean—and sets the language as the default (a default language is required due to the single
'cmap' table), and the 'locl' (Localized Forms) GSUB feature is expected to be used to access glyphs that are
appropriate for the other three languages. 

而 Source Han Sans CN 是 Region-specific Subset OpenType，只包含用来显示该地区文字所必要的字形，比如 Source Han Sans CN 就不包含日语的平假名、片假名。

>This deployment configuration includes four different subsets, and each subset includes only the glyphs that
are necessary for Simplified Chinese, Traditional Chinese, Japanese, or Korean.
These fonts are considered the most broadly usable because the 'locl' GSUB feature is not required to access
the region-specific glyphs. Instead, only the glyphs that are necessary for each region are included. This deployment
configuration is recommended for users who need only the glyphs for a specific region, and also
desire the smallest possible footprint. These fonts are expected to behave the same as conventional Simplified
Chinese, Traditional Chinese, Japanese, or Korean fonts.

所以如果在一个同时存在日语和中文的页面上使用 Source Han Sans CN 会导致日语部分 fallback 到 Noto Sans CJK SC，如果环境中存在此字体就看不出区别，如果不存在又会继续 fallback。所以我认为为了维持字体效果的统一性，这里选用 Source Han Sans/Serif SC 或 Noto Sans/Serif CJK SC 更为合适。

---
关于字体顺序，既然有 fallback 机制，为何不把 Source Han Sans/Serif SC 和 Noto Sans/Serif CJK SC 排在 Microsoft Yahei 之前？这样搭载此字体的环境可以直接使用，没有搭载的环境也可以自动 fallback 到 Microsoft Yahei。

**Comment by stecue** [comment]
我是按照[官方参考](https://github.com/adobe-fonts/source-han-serif/raw/release/download-guide-source-han.pdf)中的建议，other-->subsetOTF。而且它比较小嘛，主要需要的只是它的标点部分。不过你既然提到了，我都一起列到字体列表里也无妨。

雅黑的hinting比Noto Sans/Serif好太多。除非人人都是“视网膜”级别的显示器，雅黑默认在第一顺位不会变。但是我可以加个选项把日文片假名的第一顺为字体改成思源黑体。Anyway，这些东西都可以自己设置，只要研究出简便的保存设置的方法，随便怎么改都行了。
