### ISSUE TITLE
Broken style for Twitter voting post

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#113]
![image](https://cloud.githubusercontent.com/assets/5090766/25082807/b3e7ce40-2385-11e7-91af-44127de67ccb.png)
[さいとう なおき on Twitter: "埼玉で人並みの生活をするためには月収50万円必要らしいですけど、そんな中イラストレーターさんに質問(フリーに限らず)。私の月収は...."](https://twitter.com/_NaokiSaito/status/853875288341495808)

My script settings:
```
var CJKdefault = '"Source Han Serif SC",
var CJKSimSun= '"Source Han Serif SC",
var CJKserif = '"Source Han Serif SC",
var CJKsans = '"Source Han Serif SC",
var CJKBold = '"Source Han Serif SC",
var CJKPunct = 'Source Han Serif SC,SimHei,SimSun';

var LatinInSimSun = 'Source Serif Pro';
var LatinSans = '"Source Sans Pro",
var LatinSerif = '"Source Serif Pro",
var LatinMono = 'Consolas,"DejaVu Sans Mono"';

var FixRegular = true;
var FixMore = true;
var FixPunct = true; strings are adding to your editing area.

var usePaltForCJKText = true;
var usePaltForAll = true;
var useJustify = false;
var forceAutoSpaces = true;
var useBroaderSpaces = true;
var useXBroaderSpaces = false;
var use2XBroaderSpaces = false;
var use3XBroaderSpaces = false;
var scrollToFixAll = false;
```

**Comment by stecue** [comment]
Caused by the PUA characters used in the script. Fixed in the `master` and the `release` branches.
![screenshot_20170417_180103](https://cloud.githubusercontent.com/assets/19365079/25106552/19383be2-2398-11e7-88f6-c9e5576f66f7.png)
