### ISSUE TITLE
纯中文页面错误应用日文字形

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#123]
![image](https://cloud.githubusercontent.com/assets/5090766/26528936/f7aed776-43e8-11e7-9d0f-3924d06cad8f.png)

ver. 1.3.9

```
    var CJKdefault = 'Source Han Sans SC,"s
    var CJKSimSun= '"Source Han Serif SC",
    var CJKserif = '"Source Han Serif SC", 
    var CJKsans = '"Source Han Sans SC","M
    var CJKBold = '"Source Han Sans SC","M 
    var CJKPunct = 'Source Han Sans SC,Not
    var KanaSerif = 'Source Han Serif SC,N
    var KanaSans = 'Source Han Sans SC,Not
    var JaSerif = 'Source Han Serif SC,Not.
    var JaSans = 'Source Han Sans SC,Noto 
    var JaDefault = CJKsans; //Default fon
    ///---Latin Fonts. Note: *DO NOT* use 
    var LatinInSimSun = 'Source Serif Pro,
    var LatinSerif = 'Source Serif Pro,"PT 
    var LatinSans = '"Source Sans Pro","Op
    var LatinMono = 'Consolas,"DejaVu Sans
    var LatinDefault = LatinSans; //The de
    ///---Choose what to fix---///
    var FixRegular = true; //Also fix regu
    var FixPunct = true; //If Latin puncti
    ///=== Experimental Options. The follo
    var usePaltForCJKText = true; //If app
    var usePaltForAll = false; //If apply 
    var useJustify = false; //Make justify
    var forceAutoSpaces = true; //if enabl
    var useBroaderSpaces = true; //Now It 
    var useXBroaderSpaces = false; //It wi
    var use2XBroaderSpaces = false; //It w
    var use3XBroaderSpaces = false; //It w
    var scrollToFixAll = false; //Scoll to
    var skipJaLang = false; //Skip lang=ja
    var unifiedCJK = true; // Use Chinese 
    var FixPureLatin = false; //Appendent s
```

**Comment by stecue** [comment]
看起来是 google 吧？我这里正常啊。能不能用F12看一下显示的是什么字体？或者用[What font扩展](https://chrome.google.com/webstore/detail/whatfont/jabopobgcpjmedljpbcaablpmlmfcogm?hl=en)也可以。

**Comment by Explorare** [comment]
![image](https://cloud.githubusercontent.com/assets/5090766/26563952/3daf4c90-450d-11e7-8018-c5e815d159f6.png)

**Comment by stecue** [comment]
这啥都看不出来啊，检查的是页面空白处？。要不你右键单击“便携式耳机放大器评测报告_值友评测_什么值得买”，然后在快捷菜单里点 Inspect，（中文可能是“检查元素”之类的？），一般是快捷菜单最后一项。然后把"Style"或者"Computed"里的内容截图会比较有助于解决问题哈。

**Comment by Explorare** [comment]
![image](https://cloud.githubusercontent.com/assets/5090766/26582967/b7a9b18a-4575-11e7-9dde-b4dfc1a16c85.png)

**Comment by stecue** [comment]
fallback列表是对的。唯一有点奇怪的是我的google页面的字体列表里有Rotobo在arial之前，但这个可能与地区有关，不应该有什么区别。再要细查可以到Computed选项卡里看font-family那一栏，如果与"Style"显示的不一样可能有些线索……

或者难道你的系统里把arial映射成了某个含中文的字体？Windows的话不太清楚，Linux倒有不少办法查一下。

或者也许是Chrome的奇怪配置，不行用Firefox试一下。

**Comment by Explorare** [comment]
![image](https://cloud.githubusercontent.com/assets/5090766/26589872/c00be8aa-458b-11e7-8c60-a009cb1eff9d.png)

**Comment by stecue** [comment]
看起来一切正常，我只能想到是不是字体不全……其他页面有同样问题么？github网站（至少如果是英文界面）也没有指定中文字体，看起来正常么？

github的评论好像可以直接贴脚本全文。不妨把脚本作为附件直接拖拽过来。我没法重现的话很难debug……

**Comment by Explorare** [comment]
[FixCJK!.user.zip](https://github.com/stecue/fixcjk/files/1038783/FixCJK.user.zip)

**Comment by Explorare** [comment]
Github 没发现这个问题，似乎就 Google 页面有？错误使用了日文字体。按理来说我系统用的是 Source Hand Sans SC，首选字形应该都是简体中文才对。

**Comment by stecue** [comment]
这个脚本在我这里一切正常哈。真是令人费解……要不你看看Computed选项卡的最下面“Rendered Fonts”到底是啥吧。如果是个用不到的字体，实在不行把那个字体删掉好了……

或者右键inspect之后换到Styles选项卡，试着编辑一下font-family之后的内容。删掉arial（或者其他字体）看看是否正常。如果删掉某个字体之后可以正常fallback了，就说明那个字体被系统本身替换了。需要排查系统设置。
