### ISSUE TITLE
Strange behavior on Firefox with skia disabled。

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#127]
# Environment
Windows 10 1709 16299.19
Firefox 57.0b14
FixCJK! 1.3.9 ([Modified](https://gist.github.com/Explorare/fec8fa54dad8f8b6b3712f8000552fe7)

# Issue
There is a significant difference on rendering between the script is enabled or disabled, especially on some characters such as "自由“. I've set he default font to Source Han Sans SC on Firefox so they should be the same font no matter if the script is enabled. This issue came out when I was testing **skia** on Firefox, [here](https://github.com/snowie2000/mactype/issues/376) are more information.

# Screenshots
Script enabled
![Script enabled](https://i.imgur.com/Fhysf6v.png)

Script disabled
![Script disabled](https://i.imgur.com/0tVI6kc.png)

**Comment by stecue** [comment]
开启脚本之后，实际渲染的是“思源宋体ExtraLight”，否则是“思源宋体”。感觉有点怪啊……

**Comment by Explorare** [comment]
另一个奇怪的问题出在这个脚本 https://gist.github.com/Explorare/a3045127cb01a606d2e398a43e8706dc
我强制了使用 Serif 字体，然而只有 CJK 字符被替换成了 Source Han Serif SC，而拉丁字符被替换成了 Segoe UI，而不是 Source Serif Pro，很神秘。

Chromium 实际效果：
![image](https://user-images.githubusercontent.com/5090766/32470300-f0fc5c90-c391-11e7-99d8-01b99c0b0572.png)

FF 实际效果：
![image](https://user-images.githubusercontent.com/5090766/32470234-9d5de7f2-c391-11e7-9288-cecad28f6880.png)

Chromium 理想效果：
![image](https://user-images.githubusercontent.com/5090766/32470244-aa10b33a-c391-11e7-822f-92c7ddbad445.png)

**Comment by stecue** [comment]
关于Twitter的问题，有可能是因为这个脚本目前对拉丁字体采取的是“附加”策略。也就是说，如果网页本身就指定 Segoe UI 在Sans前面（比如字体列表是Segoe UI, AAA, BBB, Sans），那么这个脚本会把你设定的脚本放在BBB和Sans之间。即使设定的是 Serif 字体，实际渲染的字体由于Segoe UI的优先级高，仍然是Segoe UI字体。

**Comment by Explorare** [comment]
补充一点信息：

以[这个页面](https://www.gnu.org/philosophy/free-software-even-more-important.zh-cn.html)为例：

在 Chrome 中，浏览器默认字体为思源宋体，脚本的 CJKDefault 为思源黑体，CJKPunct = CJKDefault，最后页面字体为思源宋体，标点为思源宋体。

在 Firefox 中，浏览器默认字体为思源宋体，脚本设定同上，最后页面正文字体为思源宋体 ExtraLight，标点符号为思源黑体 Normal，所以我怀疑是 FF 下调用思源宋体时，必须加上字重限定 Normal，否则缺省值为最轻字重，既 ExtraLight。试着在脚本中将 CJKSans 值设为 ”Source Han Serif SC Normal“，刷新页面问题解决，不再出现正文被渲染为 ExtraLight 的问题。然而在 Chrome 下并不识别 Source Han Serif SC Normal，使用这个字体会被忽略然后 fallback 到其它字体。然而从[官方](https://typekit.com/fonts/source-han-serif-simplified-chinese)给的字重来看，默认字重是 Regular，并没有 Normal，很神秘。

最后测试得出，正确调用 Source Han Serif SC 的默认字重必须加 Regular 才能保证在 Chrome 和 FF 上获得一致效果。

**Comment by stecue** [comment]
我更新了一个版本，默认加上了"Source Han Serif SC Regular"，但是这个字体好像只在Chrome中起作用。我用的Win10和Linux版本的Firefox 57都只认"Source Han Serif SC"……

另外，FixCJK_serif.user.js是用脚本生成的只使用Serif字体的版本，可以试下哈。
