### ISSUE TITLE
B站首页 部分区域排版出错

### ISSUE THREAD

**Issue by hh0592821** [stecue/fixcjk#129]
浏览器：Chrome 63 （firefox57 下正常）
网址：www.bilibili.com
出错分区：番剧区、国创区

正常情况
![b](https://user-images.githubusercontent.com/23565750/34522954-45b62a3e-f0d0-11e7-9868-14a71dcab52a.png)
排版出错（会将其他星期同个位置的字符串显示出来）
![b](https://user-images.githubusercontent.com/23565750/34522955-46fd1de4-f0d0-11e7-88ad-c9d04b523c6c.png)
与[issues#128](https://github.com/stecue/fixcjk/issues/128)类似视乎与Chrome浏览器的排版引擎有关

**Comment by stecue** [comment]
嗯，我觉得跟#128 应该是一个问题。Chrome浏览器的Dev Tools跟Firefox差别有点大，有些属性看不到，实在头疼……

**Comment by stecue** [comment]
不好意思，这个问题和 #128 不是同一个问题。这是由于我的脚本操作了一个对象之后，网页前端脚本又对同一个对象进行操作造成了冲突导致的。我在最新的1.3.11中禁用了对这个对象的操作，B站首页的排版已经正常了，请试用！

**Comment by stecue** [comment]
我把这个issue关闭了哈。如果有问题可以再开。
