### ISSUE TITLE
非常感谢制作了这个代码！请问能否增加一个选项，选择在中英文间插入的空格是“Thin Space”还是“Hair Space”。

### ISSUE THREAD

**Issue by hmua** [stecue/fixcjk#132]
简单学习了下代码，发觉现在好像是写死的？

**Comment by hmua** [comment]
用的Stable版本

**Comment by stecue** [comment]
可能里面有些正则表达式不太好改哈，不过好像可以做出两个版本的脚本……

**Comment by hmua** [comment]
您好！想试着用最新版本代码修改一下
马上发现代码里是[标记了修改的地方](https://github.com/stecue/fixcjk/blob/master/FixCJK!.user.js#L898)的

**Comment by hmua** [comment]
我自己改了一下 用了一会儿应该没啥问题

**Comment by hmua** [comment]
嗯 我想应该可以Close Issue了
