### ISSUE TITLE
回复时引用部分出现样式代码

### ISSUE THREAD

**Issue by Explorare** [stecue/fixcjk#99]
![image](https://cloud.githubusercontent.com/assets/5090766/24400958/ffec1752-13e4-11e7-93ed-eac1ef1b8a34.png)
[ep.12 ゆうえんち / けものフレンズ](https://bgm.tv/ep/673132#post_473259)

**Comment by stecue** [comment]
是的，有时会出现，但也不一定，很麻烦。我也遇到过几次。最好能找到一个测试论坛可以专门稳定重现这个问题……

按说对编辑区域FixCJK是压根不管的，可能用了什么框架导致FixCJK没识别出来……

**Comment by Explorare** [comment]
@stecue 可以来 Bangumi 测试，发在技术版 [～技术宅真可怕～小组](https://bgm.tv/group/a)

**Comment by stecue** [comment]
@Explorare 多谢提供场地！已发帖，欢迎测试哈。
[[FixCJK测试贴]“回复时引用部分出现样式代码”](https://bgm.tv/group/topic/342483)

**Comment by stecue** [comment]
我把相应的class放到黑名单里，bmg.tv的回复问题在1.2.x分支（开发分支）中解决了。目前 1.2.x 分支的版本是1.1.52，可以升级试试看哈。

**Comment by Explorare** [comment]
Problem fixed. The new version works like a charm.

**Comment by Explorare** [comment]
[ep.1 魔の山へ / サクラクエスト](https://bgm.tv/ep/705296#post_476193)
这条回复又出现了样式代码错误，怀疑是因为用户名中存在特殊字符？

**Comment by stecue** [comment]
不是特殊字符，是小组区的讨论和章节区的讨论使用的class不一样。我把它们都加进去了(`1.2.2+`)。章节区用户名的class似乎在别的地方也有用，可能会有一些其他的超链接中的CJK部分无法修正。这个得我之后对黑名单机制再改进才能尽量减小副作用了。
